### ISSUE TITLE
where is the v2.5.8 source ?

### ISSUE THREAD

**Issue by xlla** [TomHeaven/nccl-osx#1]
I want to build pytorch for my python 3.9 but failure with 

<pre>
clang: error: unable to execute command: Illegal instruction: 4
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
</pre>

then I download the [pytorch]([pytorch-1.11.0-py37-cuda10.1-cudnn7.6.5](https://github.com/TomHeaven/pytorch-osx-build/releases/tag/v1.11.0_cu101)) and install it using python 3.7 , when I try import torch, it complain 

<pre>
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 2): Library not loaded: /Volumes/Data1/library/nccl-osx-nccl-macOS-2.5.8-release-full/build/lib/libnccl.dylib.2.5.8
  Referenced from: /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.dylib
  Reason: image not found
</pre>

I have built nccl from this repo, it is v2.5.7. I can't find v2.5.8 in this repo or original repo.

this repo
<pre>
 git tag --list
v2.5.7

</pre>

original repo
<pre>
git tag --list
v2.5.6-1
v2.5.6-2
v2.5.7-1
v2.6.4-1
</pre>

**Comment by TomHeaven** [comment]
Look at here: https://github.com/llv22/nccl-osx/releases/download/nccl-2.5.8-release-arch61/nccl-2.5.8-release-arch61.tar.gz.

**Comment by xlla** [comment]
@TomHeaven , I got it,  thanks a lot!
